name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build logic
      working-directory: ./logic
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./logic
      run: cargo test --verbose
    - name: Build examples rp
      working-directory: ./example/rp
      run: cargo build --verbose
    - name: Build examples rp235
      working-directory: ./example/rp235
      run: cargo build --verbose



